export const rentalEscrowAbi = [
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "rentalId", type: "bytes32" },
      { name: "owner", type: "address" },
      { name: "axieId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "rentalDays", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "confirmAndRelease",
    inputs: [{ name: "rentalId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRefund",
    inputs: [{ name: "rentalId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRental",
    inputs: [{ name: "rentalId", type: "bytes32" }],
    outputs: [
      { name: "borrower", type: "address" },
      { name: "owner", type: "address" },
      { name: "axieId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "rentalDays", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "released", type: "bool" },
      { name: "refunded", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "platformFeeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "rentalId", type: "bytes32", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Released",
    inputs: [
      { name: "rentalId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Refunded",
    inputs: [
      { name: "rentalId", type: "bytes32", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Paused",
    inputs: [{ name: "admin", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [{ name: "admin", type: "address", indexed: true }],
  },
] as const;
